# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2 
  encoding: utf8
  reconnect: false
  database: MMS
  pool: 5
  username: root
  password: "buongnhj"
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2 
  encoding: utf8
  reconnect: false
  database: MMS_test
  pool: 5
  username: root
  password: "buongnhj"
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
